# Generated by Django 3.0.2 on 2020-01-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CName', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
