# Generated by Django 3.0.2 on 2020-01-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=255)),
                ('Cname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Mywebsiteapp.Category')),
            ],
        ),
    ]
