# Generated by Django 3.0.2 on 2020-01-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0003_auto_20200127_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
